DROP DATABASE IF EXISTS superSightingDB;
CREATE DATABASE superSightingDB;
USE superSightingDB;

CREATE TABLE Supers(
	superID INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE Powers(
	powerID INT PRIMARY KEY AUTO_INCREMENT
);
CREATE TABLE Locations(
	locationID INT PRIMARY KEY AUTO_INCREMENT
);
CREATE TABLE Organizations(
	organizationID INT PRIMARY KEY AUTO_INCREMENT
);
